version: '2'
services:
  application:
    container_name: project_app
    image: docker.tolron.fr:5000/hackman/code
    environment:
        - project_PATH = /var/www/project
    volumes:
        - /var/www/project:/var/www/project
    tty: true
    network_mode: "bridge"
    restart: always
  db:
    container_name: project_db
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: project
        MYSQL_USER: project
        MYSQL_PASSWORD: project
    volumes:
        - "/var/lib/mysql/docker:/var/lib/mysql:rw"
    network_mode: "bridge"
    restart: always

  php:
    container_name: project_php
    image: docker.tolron.fr:5000/hackman/php7.0.8-xdebug
    volumes_from:
        - application
    volumes:
        - /var/www/project/docker/conf/php/conf.d:/usr/local/etc/php/conf.d
    links:
        - db
        - redis
    network_mode: "bridge"
    restart: always

  redis:
    container_name: project_redis
    image: docker.tolron.fr:5000/hackman/redis
    network_mode: "bridge"
    restart: always

  grunt:
    container_name: project_grunt
    image: docker.tolron.fr:5000/hackman/grunt-magento
    network_mode: "bridge"
    entrypoint:
        - /docker-entrypoint.sh
        - themeProject
    volumes:
        - /var/www/project:/app
    links:
        - redis
        - db

  webserver:
    container_name: project_webserver
    image: docker.tolron.fr:5000/hackman/nginx
    links:
        - php
        - db
        - redis
    volumes_from:
        - application
    volumes:
        - /var/www/project/docker/conf/nginx/sites-enabled:/etc/nginx/sites-enabled
        - /var/www/empty:/etc/nginx/sites-available
    network_mode: "bridge"
    environment:
        VIRTUAL_HOST: project.local
    restart: always